было:  const f = x => x <= 1 ? 1 : x * f(x - 1);
стало:            x => x <= 1 ? 1 : x * arguments.callee(x - 1)
Как такая функция может вызвать сама себя? У неё нет имени.